# Generated by Django 6.0.5 on 2026-05-21 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Где выполнять привычку.",
                        max_length=255,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Когда выполнять привычку.", verbose_name="Время"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Что именно делает пользователь.",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="True — привычка-награда, False — полезная привычка.",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Раз в сколько дней повторять. От 1 до 7.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность, дней",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем себя поощрить. Нельзя задавать вместе со связанной привычкой.",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Не более 120 секунд.",
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="Время выполнения, сек",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Если True — привычка отображается в списке публичных.",
                        verbose_name="Публичная",
                    ),
                ),
                (
                    "last_notified_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Время последнего напоминания.",
                        null=True,
                        verbose_name="Последнее напоминание",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Указывается только для полезных привычек. "
                        "Может ссылаться только на приятную привычку.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users_of_this_reward",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ("time", "id"),
            },
        ),
    ]
