upstream habit_backend {
    server web:8000;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 10M;

    location /static/ {
        alias /app/static/;
        access_log off;
        expires 7d;
    }

    location /media/ {
        alias /app/media/;
        access_log off;
        expires 7d;
    }

    location / {
        proxy_pass http://habit_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }
}